services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  app:
    build: .
    command: bash -c "python models.py && python server.py"
    env_file:
      - .env
    environment:
      - HOST_DB=db
    ports:
      - 5001:5001
    depends_on:
      - db

volumes:
  postgres_data: